### ISSUE TITLE
:bug: Remote catalog continues to contain parquet files

### ISSUE THREAD

**Issue by larsyencken** [owid/etl#1261]
## Problem

Despite having merged a PR that [removed Parquet from the catalog](https://github.com/owid/etl/pull/1252), we still see a ton of Parquet files in the `data-catalog` repo.

## Todo

- [x] https://github.com/owid/ops/pull/76
- [x] https://github.com/owid/etl/pull/1262
- [x] Confirm that the catalog is free from Parquet

**Comment by larsyencken** [comment]
It needed a manual prune of the last catalog files, but they're no longer being generated now.
