### ISSUE TITLE
Tracking issue: improve `etl-datadiff`

### ISSUE THREAD

**Issue by Marigold** [owid/etl#2107]
Suggested improvements:

* [x] Move datadiff to automated staging server which would give it persistence (and a new commit wouldn't be rebuilding everything from scratch)
* [x] Efficiently pick datasets to compare when using `REMOTE` based on checksum from the catalog (this is essential for moving it to automated staging server, otherwise we'd download all datasets from the catalog)
* [x] Use the correct base branch of data, e.g. by using `git-lfs` and `data-catalog`
* [ ] Avoid repeating same origins diff for multiple indicators - this tends to clutter the output
  - This could be done by collecting all unique origins for a dataset and comparing them in a special section. Then, for variables, we'd just mention the name of the changed origin.
* [ ] Make it very easy to diff against the previous version of a single dataset

**Comment by Marigold** [comment]
Keep it open a bit longer.

**Comment by lucasrodes** [comment]
FWIW, I am deprecating `datadiff` in favor of new `etlcli diff`

See https://github.com/owid/ops/pull/147

**Comment by Marigold** [comment]
Most of these got implemented.
