### ISSUE TITLE
Roadmap: data engineering 2024

### ISSUE THREAD

**Issue by larsyencken** [owid/etl#2136]
[← 2023](https://github.com/owid/etl/issues/1285) | [↑ Engineering](https://github.com/owid/engineering/issues/39)

## 2024 Q1

- [x] #1964 
- [x] Support editing metadata from the Grapher admin
- [x] https://github.com/owid/owid-issues/issues/1365
- [x] https://github.com/owid/etl/pull/2328

## 2024 Q2
- https://github.com/owid/etl/issues/2610
- https://github.com/owid/etl/issues/2580
- https://github.com/owid/etl/issues/2365

## 2024 Q4

- [x] Anomaly detection prototype

## Candidates

- [ ] Browsable data catalog
- [ ] Synchronise ETL DAG into MySQL
- [ ] Link generated CSVs with CSV-based explorers
- [ ] Link indicators with their previous versions
- [ ] Move explorer TSV generation into the ETL
