### ISSUE TITLE
Staging servers have non-deterministic failures

### ISSUE THREAD

**Issue by larsyencken** [owid/etl#3276]
## Problem

Anecdotally, it seems like there's often a random failure in a staging server pipeline, but if you manually retry it on Buildkite it works.

## Expected behaviour

We'd hope for things to work the first time

## Gathering more information

- Could we periodically review recent builds on each branch?
- Could we dump all pipelines including failures and retries using the API?
- Are there additional steps that should have automatic retries

## Failure types

- [ ] [github authentication issue](https://buildkite.com/our-world-in-data/etl-automated-staging-environment/builds/9110#0191e5fc-b792-4615-8c1e-d7eec5a31421)
  - If github cannot be accessed, exit with code 13. This can be used to retry the step
- [x] [poetry cannot find installation candidates](https://buildkite.com/our-world-in-data/owid-catalog-unit-tests/builds/14751#0191e55a-e4d8-4c44-9da7-c14a37dd82ef)
  - This can be hopefully fixed by switching to `uv` package manager #3257 
- [ ] [Admin API error](https://buildkite.com/our-world-in-data/etl-automated-staging-environment/builds/9700#0191c771-e035-46ae-8273-62d514343b04)
  - This should go away after merging with master. There are race conditions in Buildkite and retry mechanism has been added to master this week

**Comment by larsyencken** [comment]
Mojmir to review a few recent failures and add retries for them.

We're missing data over time on how this is going, something that's not easy for staging servers since they routinely have real failures due to errors in people's code.

A false positive from CI is if a retry of the same check succeeds the next time.

**Comment by larsyencken** [comment]
Closing this for now, but if we start seeing more we should re-open it.
