### ISSUE TITLE
Parquet files are not being repacked

### ISSUE THREAD

**Issue by larsyencken** [owid/etl#357]
Parquet files are currently much larger than feather files, but it's simply because the repacking support in `Table.to_feather()` has not been added to `Table.to_parquet()`. If we add this missing stanza, we should see smaller and more efficient parquet files come out the other side.

## Todo

- [x] https://github.com/owid/owid-catalog-py/pull/56
- [x] Update owid-catalog-py
- [x] Force rebuild all existing parquet files
- [x] Verify whether the file size changed

**Comment by larsyencken** [comment]
@danielgavrilov Current index stats after rebuilding:

- Feather: 3.88G
- Parquet (packed): 5.97G (1.54x bigger)
- Parquet (unpacked): 7.59G (1.95x bigger)

Overall, repacking reduced parquet file sizes by 27%, which is a pretty decent win. There might be other gains to be made by varying compression algorithm, but that's another day's experimentation.

**Comment by larsyencken** [comment]
I should add, no correctness issues were found duringhttps://github.com/owid/owid-catalog-py/issues/57 that would affect the correctness of the files generated, so we can have confidence in these numbers.

**Comment by danielgavrilov** [comment]
@larsyencken They are still unexpectedly big:

<img width="960" alt="Screenshot 2022-08-03 at 17 37 16" src="https://user-images.githubusercontent.com/1308115/182662458-43029b98-d8a1-4c0a-90e0-58b3d5c4d7fe.png">

**187 MB** parquet vs **45 MB** feather. 

If I run the conversion from feather to parquet, I get much smaller file sizes:

```python
cat = catalog.RemoteCatalog()
food_explorer_df = cat.find(dataset="faostat_food_explorer").iloc[0].load()
food_explorer_df.to_feather("faostat_food_explorer.feather") # 47.3 MB (but it's 45.1 MB on spaces somehow!)
food_explorer_df.to_parquet("faostat_food_explorer.parquet") # 63.5 MB (vs 187 MB on spaces)
```

**Comment by danielgavrilov** [comment]
Opened a new issue:

- https://github.com/owid/etl/issues/363
