### ISSUE TITLE
Upsert Table into `tables`

### ISSUE THREAD

**Issue by Marigold** [owid/etl#449]
## Context

When we created the ETL and made a space for data science, it was clear that datasets and variables were not enough, and that there should be a table level in between, since it's the table level that maps 1:1 with data frames in memory and files on disk. However, our site's data model does not include this table level yet.

## What

Add the table level to the data model for our site and upsert to it when runing `etl --grapher`

## Why

- We want to offer better data downloads for people, and this means having grouping our variables into tables
  - It makes sense that these should be shared with our data model
- We base explorers off tables, so to power explorers from MySQL (to improve metadata reuse) would require knowing about these tables in MySQL
- We believe that sharing the same data model between the ETL and MySQL will bring real benefits and opportunities that are hard to predict in advance

## Todo

- [ ] Create new ORM entity `GrapherTable` that represents our `catalog.Table` entity.
- [ ] Run a migration to add the new table
- [ ] Upsert to it in MySQL when running `etl --grapher`

## Technical notes

- Using Tables doesn't get us any immediate value, so it's likely a low priority at the moment.
- There's WIP branch [449-upsert-table-into-tables](https://github.com/owid/etl/compare/master...449-upsert-table-into-tables) with proposed changes.

**Comment by danyx23** [comment]
@Marigold pinging you again during issue triage :). Please flesh this out in a bit more so we can schedule it. Thanks!

**Comment by danyx23** [comment]
My hunch is that this will become more urgent once we start working on implementing the data catalog. Leaving this open but we'll probably not get around to doing this this year

**Comment by larsyencken** [comment]
The issue description described a "what", but was missing a "why". I did my best to fill that out here.
