### ISSUE TITLE
Stop upserting to `data_values` table from ETL

### ISSUE THREAD

**Issue by Marigold** [owid/etl#571]
## Problem

Upserts to `data_values` during `etl --grapher` can be slooow and take up significant space in MySQL. Now that we can bake & preview from parquet files, we don't need to upsert to `data_values` anymore.

## New dev workflow and deploys from ETL

Since we won't be using `data_values` for storing data, how is ETL development going to look like? Right now you can run `etl --grapher` to upsert data into `data_values` and then check them out from local admin. This will be replaced by parquet files from your local data catalog. You'll have to point `CATALOG_PATH` to your local ETL catalog and if using docker, create a symlink in grapher and point it there.

To get data into production grapher, you'll have to merge your PR first, let ETL rebuild & republish the catalog and then run `etl --grapher` to upsert variables (without `data_values`). Such manual deploys are quite complex, so setting up automatic grapher upserts would be preferred. After every merge to ETL we'll republish our catalog and run `etl --grapher` to upsert everything to production (/staging).

(An alternative would be to keep using mix of data_values & parquet files, but that'd become messy very soon.)

## TODO

* [ ] make every dev point env `CATALOG_PATH` to their local ETL catalog
* [ ] stop upserting to `data_values`
* [ ] prune all `data_values` coming from ETL (there's a ton of them!)
* [ ] benchmark upserts without `data_values`, is that fast enough? (do we even need threading?)
