### ISSUE TITLE
Python 3.11 support

### ISSUE THREAD

**Issue by larsyencken** [owid/etl#642]
## Overview

Python 3.11 has now been released. The major benefit is performance, which is estimated to be 25% better overall than Python 3.10 (see: [release notes](https://docs.python.org/3/whatsnew/3.11.html)).

## Todo

- [x] Support building the ETL on Python 3.11
  - [x] Add python 3.11 to the `etl-build` template https://github.com/owid/ops/commit/10c917b23375007f787dc601557741a3053f76a5
  - [x] Add python 3.11 to the live `etl-build-1` server 
  - [ ] ~~Get `pyarrow` working cleanly on the remote server: https://github.com/owid/ops/pull/37~~
  - [x] https://github.com/owid/owid-catalog-py/pull/73
  - [x] https://github.com/owid/etl/pull/695
- [x] Verify ETL steps succeed on Python 3.11
  - [x] Successful build from scratch https://buildkite.com/our-world-in-data/python-3-dot-11-full-rebuild-from-scratch/builds/2
- [x] Switch production ETL to Python 3.11
  - [x] Install Python 3.11 on analytics
  - [x] Update ETL production scripts to use Python 3.11

**Comment by larsyencken** [comment]
The best approach is likely to be just to wait for `pyarrow` to ship binary packages.

**Comment by larsyencken** [comment]
@Marigold Put together two PRs for this now, one for `etl` and one for `owid-catalog-py`. If they both pass CI, I'd suggest we merge them, and even consider running our prod ETL on Python 3.11, which is meant to be faster.

**Comment by larsyencken** [comment]
✓ Installed Python 3.11 on `analytics`, using steps from https://github.com/owid/ops/blob/main/templates/etl-build/init.sh#L142

**Comment by larsyencken** [comment]
Build was successful, the virtualenv on analytics was rebuilt as well using `poetry env use python3.11` before `poetry install`.
