### ISSUE TITLE
Regions and aliases that must be corrected

### ISSUE THREAD

**Issue by pabloarosado** [owid/etl#796]
## Changes to make

Regions whose name needs to be changed:
* Turkey -> Türkiye. Should we apply this change? I think so far all our country names are free of accents and umlauts. So this change feels like an outlier.
* Timor -> Timor-Leste. Since Timor refers to the entire island (where West Timor belongs to Indonesia), but we usually refer to the country East Timor within the island.

Aliases to be corrected:
* Yemen Arab Republic should be an alias of former region North Yemen, instead of Yemen. I wrote this down some time ago, but I think it has already been fixed. @larsyencken was it you?

Additional changes:
* We need a short name for "Democratic Republic of Congo", for example for Marimekko charts. What about "DR Congo"?

## Todo

- [ ] Countries regions dataset change in ETL
- [ ] Update grapher so that new regions actually show on map
- [ ] Fix every existing country mapping file in ETL

**Comment by lucasrodes** [comment]
> Turkey -> Türkiye. Should we apply this change? I think so far all our country names are free of accents and umlauts. So this change feels like an outlier.

We can use "Turkiye" instead, but I think we should consider this rename [[ref](https://www.aljazeera.com/news/2022/6/2/un-registers-turkiye-as-new-country-name-for-turkey)].

> Timor -> Timor-Leste. Since Timor refers to the entire island (where West Timor belongs to Indonesia), but we usually refer to the country East Timor within the island.

An alternative name could be "East Timor". 

> 
Regions whose name needs to be changed:

Turkey -> Türkiye. Should we apply this change? I think so far all our country names are free of accents and umlauts. So this change feels like an outlier.
Timor -> Timor-Leste. Since Timor refers to the entire island (where West Timor belongs to Indonesia), but we usually refer to the country East Timor within the island.
Aliases to be corrected:

Yemen Arab Republic should be an alias of former region North Yemen, instead of Yemen. I wrote this down some time ago, but I think it has already been fixed. @larsyencken was it you?
Additional changes:

> We need a short name for "Democratic Republic of Congo", for example for Marimekko charts. What about "DR Congo"?

I like it!

**Comment by spoonerf** [comment]
This sounds great and I think we should definitely do it. However, I don't think it is currently possible to use accents in grapher? I made a quick experiment [here](https://neurath.owid.cloud/admin/charts/5864/edit) and the 'ü' doesn't show up.

**Comment by edomt** [comment]
Thanks Pablo!

I'm a bit hesitant about Turkey – I feel like the new name hasn't "caught on" at all yet. For others like Timor, or past ones like Eswatini, it was very clear we were showing a name that people had stopped using. For Turkey, it seems to me that everyone still calls it "Turkey" (including [Wikipedia](https://en.wikipedia.org/wiki/Turkey)).

I'm curious to know if others have an opinion about this!

**Comment by Marigold** [comment]
> I'm a bit hesitant about Turkey – I feel like the new name hasn't "caught on" at all yet

(Sorry for chiming in. From my experience changing Czech Republic -> Czechia hasn't caught on either. Organisations and government has only started changing it recently after 6 years of making it official. Residents don't care much.)

**Comment by eoo-owid** [comment]
Agree with Hannah - I understand there are tradeoffs but my view is that the bar for changing country names should be super high. The idea of the OWID standardised names is to go with the most widely known and understandable name, and in the case of Turkiye that's not (yet) the case. Changing country names also break people's code etc. So my vote would be not to change it

**Comment by maxroser** [comment]
Very much agree with the high bar for any country name changes. 
–> Before we make any change we should discuss among team-leads whether we want to actually make the country name change(s). That's because it has an impact on all teams – from engineering, to product, to writing and data work.

And also agree that we should stick with commonly known country names (i.e. Turkey instead of Türkiye).

**Comment by pabloarosado** [comment]
Thanks everyone! I agree, we don't have to change Turkey for now.
I hope you all agreed on the other suggested changes, and feel free to add any other changes here. I'm planning to implement the changes probably by next week at some point.

**Comment by pabloarosado** [comment]
By the way, just to be clear, nobody was planning to make country name changes any regularly. I just suggested these changes because we are in the middle of [a refactor of our countries-regions dataset](https://github.com/owid/etl/issues/779). Other than that, hopefully, we don't have to make any changes for a long time, so there's no need to worry about it.

**Comment by edomt** [comment]
@pabloarosado I'll add this to the agenda of tomorrow's team leads meeting, and I'll come back after to confirm.

**Comment by edomt** [comment]
Hey @pabloarosado – we've confirmed the following:

- `Timor` -> `East Timor`
- `Democratic Republic of Congo` can be shortened to `DR Congo` when needed
- `Turkey`: no change

**Comment by bastianherre** [comment]
Prompted by the [discussion about the countries-regions dataset](https://github.com/owid/etl/pull/824#issuecomment-1431741747), I propose to change the names used for two historical states:

* `Eritrea and Ethiopia` -> `Ethiopia (former)`: this makes this case analogous to 'Sudan (former)', when South Sudan was still part of the country; and it makes clear that the data refers to one country, not two.
* `United Korea` -> `Korea`: this switches to the commonly used historical name; and it yields more sensible Google search results for the unassuming user.

As opposed to some of the changes considered above, this likely affects few datasets.

**Comment by edomt** [comment]
When we get to it, we should probably do `Faeroe Islands` -> `Faroe Islands` as well. 

Our current spelling is technically correct but very rare:

<img width="1167" alt="image" src="https://user-images.githubusercontent.com/7103774/232712082-90789079-1f1d-409b-bee3-617d64d35889.png">
